require('core.options')
require('core.keymaps')
require('core.plugins')
require('core.colorscheme')
-- require('plugin.coc')
require('plugin.nvim-comment')
require('plugin.bookmarks')
require('plugin.gitsigns')
require('plugin.nvim-tree')
require('plugin.telescope')
require('plugin.which-key')
require('plugin.alpha-nvim')
require('plugin.project')
require('plugin.lspconfig')
require('plugin.nvim-cmp')
require('plugin.treesitter')
